createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table 'Currency Exchange'
			lineageTag: 558d7fc8-8f78-4bca-9d05-5de68abfda02

			column Date
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: 58bd0eb3-97e7-4364-a728-2b536e8797c8
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column FromCurrency
				dataType: string
				lineageTag: f0fc6ed4-63f6-4904-a1c2-c02d8f6f2de1
				summarizeBy: none
				sourceColumn: FromCurrency

				annotation SummarizationSetBy = Automatic

			column ToCurrency
				dataType: string
				lineageTag: da280a5c-c30a-4b01-a302-dfe11b62a3c6
				summarizeBy: none
				sourceColumn: ToCurrency

				annotation SummarizationSetBy = Automatic

			column Exchange
				dataType: double
				lineageTag: c095d13c-a826-4504-9945-61b9f16c84a4
				summarizeBy: sum
				sourceColumn: Exchange

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition 'Currency Exchange' = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    #"dbo_Currency Exchange" = Source{[Schema="dbo",Item="Currency Exchange"]}[Data]
						in
						    #"dbo_Currency Exchange"

			annotation PBI_ResultType = Table

		table Customer
			lineageTag: 93961b88-0b38-45c3-982d-0e347010330b

			column CustomerKey
				dataType: int64
				formatString: 0
				lineageTag: c0c17d79-0df4-44d6-9270-d542ad0bcdfa
				summarizeBy: none
				sourceColumn: CustomerKey

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: 5582147b-4479-4230-851d-b32277a79529
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column Name
				dataType: string
				lineageTag: 4949d982-2e9e-40b2-80ae-c80e6357bf7b
				summarizeBy: none
				sourceColumn: Name

				annotation SummarizationSetBy = Automatic

			column Address
				dataType: string
				lineageTag: 595f26eb-96c3-40ff-a14d-0fb940c5b9a8
				summarizeBy: none
				sourceColumn: Address

				annotation SummarizationSetBy = Automatic

			column City
				dataType: string
				lineageTag: 69da70ca-fccc-4cbd-b6ca-aa8328fe8f11
				summarizeBy: none
				sourceColumn: City

				annotation SummarizationSetBy = Automatic

			column 'State Code'
				dataType: string
				lineageTag: 4ee1000d-d2bc-4a0a-9b13-feccae65e412
				summarizeBy: none
				sourceColumn: State Code

				annotation SummarizationSetBy = Automatic

			column State
				dataType: string
				lineageTag: 88899579-78e2-4739-bf97-2d75b6e5feab
				summarizeBy: none
				sourceColumn: State

				annotation SummarizationSetBy = Automatic

			column 'Zip Code'
				dataType: string
				lineageTag: 82fdc53b-4648-4e27-81dd-0095990d94aa
				summarizeBy: none
				sourceColumn: Zip Code

				annotation SummarizationSetBy = Automatic

			column 'Country Code'
				dataType: string
				lineageTag: c3a4f56b-9818-4c2d-bcec-feb2e08612ce
				summarizeBy: none
				sourceColumn: Country Code

				annotation SummarizationSetBy = Automatic

			column Country
				dataType: string
				lineageTag: d2a06dc9-84f4-41df-bab7-db7371ce0915
				summarizeBy: none
				sourceColumn: Country

				annotation SummarizationSetBy = Automatic

			column Continent
				dataType: string
				lineageTag: 4b8ed967-7296-4c4d-b1e8-bedec951d916
				summarizeBy: none
				sourceColumn: Continent

				annotation SummarizationSetBy = Automatic

			column Birthday
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: 4e1dd9ed-c054-4d23-8f3a-839438d84c2c
				summarizeBy: none
				sourceColumn: Birthday

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Age
				dataType: int64
				formatString: 0
				lineageTag: 9a61fbf3-1718-466d-8d0a-77e97220a6e6
				summarizeBy: sum
				sourceColumn: Age

				annotation SummarizationSetBy = Automatic

			partition Customer = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data]
						in
						    dbo_Customer

			annotation PBI_ResultType = Table

		table Date
			lineageTag: c9943558-b048-4df6-850c-27318ad94d7f
			dataCategory: Time

			column Date
				dataType: dateTime
				isKey
				formatString: m/d/yyyy
				lineageTag: e2fae708-c793-4688-b7c9-da6c2184b930
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Year
				dataType: int64
				formatString: 0
				lineageTag: 064ae977-a7a0-4cb2-af5c-d034b9d4575a
				summarizeBy: none
				sourceColumn: Year

				annotation SummarizationSetBy = Automatic

			column 'Year Quarter'
				dataType: string
				lineageTag: 79c22d55-2156-443b-a4cb-510add137594
				summarizeBy: none
				sourceColumn: Year Quarter
				sortByColumn: 'Year Quarter Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Year Quarter Number'
				dataType: int64
				formatString: 0
				lineageTag: 5ed21f56-65cb-43a0-905a-0672e491c337
				summarizeBy: none
				sourceColumn: Year Quarter Number

				annotation SummarizationSetBy = Automatic

			column Quarter
				dataType: string
				lineageTag: 32214b16-8449-416e-8c6b-2c7a707bcb6d
				summarizeBy: none
				sourceColumn: Quarter

				annotation SummarizationSetBy = Automatic

			column 'Year Month'
				dataType: string
				lineageTag: d42fb1f9-dc04-4590-b23b-18e390da216c
				summarizeBy: none
				sourceColumn: Year Month
				sortByColumn: 'Year Month Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Year Month Short'
				dataType: string
				lineageTag: 1fe26123-ed60-44c8-8154-ef11258fd5b3
				summarizeBy: none
				sourceColumn: Year Month Short
				sortByColumn: 'Year Month Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Year Month Number'
				dataType: int64
				formatString: 0
				lineageTag: 12e70050-1af1-4886-8541-743cdc2328f7
				summarizeBy: none
				sourceColumn: Year Month Number

				annotation SummarizationSetBy = Automatic

			column Month
				dataType: string
				lineageTag: 312cf201-63eb-4dce-8942-86934fd3b24d
				summarizeBy: none
				sourceColumn: Month
				sortByColumn: 'Month Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Month Short'
				dataType: string
				lineageTag: 9686650d-a033-46e7-ba6d-ae066c613ea2
				summarizeBy: none
				sourceColumn: Month Short
				sortByColumn: 'Month Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Month Number'
				dataType: int64
				formatString: 0
				lineageTag: 20bf9b00-13bc-4964-be8c-fcc504ee0e14
				summarizeBy: none
				sourceColumn: Month Number

				annotation SummarizationSetBy = Automatic

			column 'Day of Week'
				dataType: string
				lineageTag: e05b7f71-d597-48d1-8817-59017f82d85f
				summarizeBy: none
				sourceColumn: Day of Week
				sortByColumn: 'Day of Week Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Day of Week Short'
				dataType: string
				lineageTag: 2b570fb6-5f24-4378-a3ff-b0a9fbe8b9ab
				summarizeBy: none
				sourceColumn: Day of Week Short
				sortByColumn: 'Day of Week Number'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Day of Week Number'
				dataType: int64
				formatString: 0
				lineageTag: 4268e88d-117f-45e4-8088-33e03b63de37
				summarizeBy: none
				sourceColumn: Day of Week Number

				annotation SummarizationSetBy = Automatic

			column 'Working Day'
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: 2e2cf5a0-3689-4a80-bfab-900a4b2970d5
				summarizeBy: none
				sourceColumn: Working Day

				annotation SummarizationSetBy = Automatic

			column 'Working Day Number'
				dataType: int64
				formatString: 0
				lineageTag: f8ee95ee-7772-4842-ab96-fc762db1710d
				summarizeBy: none
				sourceColumn: Working Day Number

				annotation SummarizationSetBy = Automatic

			hierarchy 'Date Hierarchy'
				lineageTag: 431c0aea-cd83-40ef-9a06-e670cf3df107

				level Year
					lineageTag: 74c0d31a-9f89-41be-ad3f-2f8a4b1ba1ff
					column: Year

				level Quarter
					lineageTag: e4273c90-314d-48b0-9e2f-ba9e02d1bc64
					column: Quarter

				level 'Month Short'
					lineageTag: f32aaa3a-37c6-466b-b389-b6fe0a0a6aed
					column: 'Month Short'

				level Date
					lineageTag: f0c0b2d9-586b-44af-a629-2992bcb3cd57
					column: Date

			partition Date = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    dbo_Date = Source{[Schema="dbo",Item="Date"]}[Data]
						in
						    dbo_Date

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Sales
			lineageTag: 4187ee1a-85c0-4cc3-bbe5-729575b85aaf

			column 'Order Number'
				dataType: int64
				formatString: 0
				lineageTag: c470ec12-ff82-4949-90f3-c986b0c3d684
				summarizeBy: sum
				sourceColumn: Order Number

				annotation SummarizationSetBy = Automatic

			column 'Line Number'
				dataType: int64
				formatString: 0
				lineageTag: 79b7c14a-c064-446a-8924-e38de6f26cce
				summarizeBy: sum
				sourceColumn: Line Number

				annotation SummarizationSetBy = Automatic

			column 'Order Date'
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: c1fdfa39-2398-440f-ac05-b35d079b43d0
				summarizeBy: none
				sourceColumn: Order Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column 'Delivery Date'
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: 063616c0-f40a-489a-a145-735b277e4bdc
				summarizeBy: none
				sourceColumn: Delivery Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column CustomerKey
				dataType: int64
				formatString: 0
				lineageTag: a66e164e-2cc4-4199-a37b-abd41d7b50dd
				summarizeBy: none
				sourceColumn: CustomerKey

				annotation SummarizationSetBy = Automatic

			column StoreKey
				dataType: int64
				formatString: 0
				lineageTag: 906b3b87-75b0-43fb-9e66-ee30b8db1f60
				summarizeBy: none
				sourceColumn: StoreKey

				annotation SummarizationSetBy = Automatic

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 9e5756dd-64be-4f83-8008-ae87a04c8369
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column Quantity
				dataType: int64
				formatString: 0
				lineageTag: 2382e901-c313-49f0-972c-a4c84afbeb3c
				summarizeBy: sum
				sourceColumn: Quantity

				annotation SummarizationSetBy = Automatic

			column 'Unit Price'
				dataType: decimal
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: c5f3b1f0-0a92-4f40-9d6e-e6c93db51e23
				summarizeBy: sum
				sourceColumn: Unit Price

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			column 'Net Price'
				dataType: decimal
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 50754b3f-f213-4989-894e-4417031ed094
				summarizeBy: sum
				sourceColumn: Net Price

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			column 'Unit Cost'
				dataType: decimal
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: b805dcd1-b7f0-487f-91aa-734cea58bc7a
				summarizeBy: sum
				sourceColumn: Unit Cost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			column 'Currency Code'
				dataType: string
				lineageTag: a72206df-181c-43b3-9f99-da7178ef98d3
				summarizeBy: none
				sourceColumn: Currency Code

				annotation SummarizationSetBy = Automatic

			column 'Exchange Rate'
				dataType: double
				lineageTag: cd6929b4-4d36-426d-9e4b-0caf373bc043
				summarizeBy: sum
				sourceColumn: Exchange Rate

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition Sales = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    dbo_Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
						in
						    dbo_Sales

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Store
			lineageTag: 2035c446-618f-42e2-bcb6-d7487b8e1a91

			column StoreKey
				dataType: int64
				formatString: 0
				lineageTag: c21081a5-16bc-4e77-988d-8d7a4269a890
				summarizeBy: none
				sourceColumn: StoreKey

				annotation SummarizationSetBy = Automatic

			column 'Store Code'
				dataType: int64
				formatString: 0
				lineageTag: 4c949d48-03ac-402a-9395-349f3f4013eb
				summarizeBy: count
				sourceColumn: Store Code

				annotation SummarizationSetBy = Automatic

			column Country
				dataType: string
				lineageTag: a23a3795-b1b7-408e-b474-2383a5057f3e
				summarizeBy: none
				sourceColumn: Country

				annotation SummarizationSetBy = Automatic

			column State
				dataType: string
				lineageTag: c235c4d6-ae3c-4060-917b-a89a01ea4da3
				summarizeBy: none
				sourceColumn: State

				annotation SummarizationSetBy = Automatic

			column Name
				dataType: string
				lineageTag: 637c3d05-d1cb-41ec-9256-628ab39a25a4
				summarizeBy: none
				sourceColumn: Name

				annotation SummarizationSetBy = Automatic

			column 'Square Meters'
				dataType: int64
				formatString: 0
				lineageTag: 6101b1af-8961-49f4-8ee6-d23d941067c4
				summarizeBy: sum
				sourceColumn: Square Meters

				annotation SummarizationSetBy = Automatic

			column 'Open Date'
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: dadf767f-251b-4b87-9ec8-de959d891943
				summarizeBy: none
				sourceColumn: Open Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column 'Close Date'
				dataType: dateTime
				formatString: m/d/yyyy
				lineageTag: fe572261-bd7b-4f12-aee7-f426ff02c5ee
				summarizeBy: none
				sourceColumn: Close Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Status
				dataType: string
				lineageTag: e49cbd9f-20bd-4caa-8026-c60756de80b7
				summarizeBy: none
				sourceColumn: Status

				annotation SummarizationSetBy = Automatic

			partition Store = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    dbo_Store = Source{[Schema="dbo",Item="Store"]}[Data]
						in
						    dbo_Store

			annotation PBI_ResultType = Table

		table Product
			lineageTag: a1fdf9a5-8800-4f4b-bd3b-39a814fb068d

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 8798e1f0-3f00-45e7-b039-65fbe5f579ee
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column 'Product Code'
				dataType: string
				lineageTag: c0993b99-789a-4a7e-a252-6ce9bfe1327a
				summarizeBy: none
				sourceColumn: Product Code

				annotation SummarizationSetBy = Automatic

			column 'Product Name'
				dataType: string
				lineageTag: 2992130f-f919-4506-a755-160fcbfd3997
				summarizeBy: none
				sourceColumn: Product Name

				annotation SummarizationSetBy = Automatic

			column Manufacturer
				dataType: string
				lineageTag: 535db9a8-4404-4b45-8e48-362506411825
				summarizeBy: none
				sourceColumn: Manufacturer

				annotation SummarizationSetBy = Automatic

			column Brand
				dataType: string
				lineageTag: 3200c6e1-ffd8-44dc-a652-e6940b08caf2
				summarizeBy: none
				sourceColumn: Brand

				annotation SummarizationSetBy = Automatic

			column Color
				dataType: string
				lineageTag: b3c2ebc2-292d-4e39-b23e-d9dfa46d177f
				summarizeBy: none
				sourceColumn: Color

				annotation SummarizationSetBy = Automatic

			column 'Weight Unit Measure'
				dataType: string
				lineageTag: ee16abe8-877b-41d6-a0fb-fbb5bad1e738
				summarizeBy: none
				sourceColumn: Weight Unit Measure

				annotation SummarizationSetBy = Automatic

			column Weight
				dataType: double
				lineageTag: 8eaef65f-d46c-48c0-9edb-9dbce0bd9eab
				summarizeBy: none
				sourceColumn: Weight

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Unit Cost'
				dataType: decimal
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 60faf266-8f6c-42b5-9661-446f84f8e478
				summarizeBy: none
				sourceColumn: Unit Cost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			column 'Unit Price'
				dataType: decimal
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: a5b7c4ef-15f5-4333-bbd7-d8fee2177594
				summarizeBy: none
				sourceColumn: Unit Price

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			column 'Subcategory Code'
				dataType: int64
				formatString: 0
				lineageTag: 39ebca05-450c-4faf-b669-6a05d0dabe2d
				summarizeBy: none
				sourceColumn: Subcategory Code

				annotation SummarizationSetBy = Automatic

			column Subcategory
				dataType: string
				lineageTag: 4d66942a-cb8a-4f64-b1eb-8b02a1b1fba5
				summarizeBy: none
				sourceColumn: Subcategory

				annotation SummarizationSetBy = Automatic

			column 'Category Code'
				dataType: int64
				formatString: 0
				lineageTag: ded30802-8757-470b-8284-48dd16a8c9b8
				summarizeBy: none
				sourceColumn: Category Code

				annotation SummarizationSetBy = Automatic

			column Category
				dataType: string
				lineageTag: e11bdbd5-229f-4f46-8174-1214dbe64537
				summarizeBy: none
				sourceColumn: Category

				annotation SummarizationSetBy = Automatic

			partition Product = m
				mode: import
				source =
						let
						    Source = Sql.Database("DESKTOP-PONL6H6", "Contoso V2 1M"),
						    dbo_Product = Source{[Schema="dbo",Item="Product"]}[Data]
						in
						    dbo_Product

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DAX
			lineageTag: ae8e2a89-c83d-4295-83fe-4e256ae39fb3

			measure 'Sales Amount' = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 9eece577-bbce-43c2-a38e-90e39d9aad03

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure FLOWERBOUND = FLOWERBOUND ( 0 )
				formatString: 0
				lineageTag: ec382886-ae93-4392-a2c1-66a0edffc298

			measure FPY = FPY ( [Sales Amount] )
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: d81d3f67-3d70-43bd-8bfa-a20adba39ede

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure FYOY = FYOY ( [Sales Amount] )
				formatString: #,0.00
				lineageTag: 280f262b-caa4-4ffe-bbb5-6c7bd95be52e

			measure FREFLINE2 = FREFLINE2 ( 0.25 )
				lineageTag: 5aba0dbd-547e-400f-a333-95dd92f2d717

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure FREFLINE3 = FREFLINE3 ( 0.5 )
				lineageTag: 8320da03-f49e-4132-82dd-a507dd641a08

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure FREFLINE4 = FREFLINE4 ( 0.75 )
				lineageTag: 08d6b545-9e60-4d82-b816-27d8db20eaa0

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure FREFLINE5 = FREFLINE5 ( 1 )
				formatString: 0
				lineageTag: 68f12876-1228-4237-9521-0a82b2ed03f8

			measure FREFLINE1 = FREFLINE1 ( 0 )
				formatString: 0
				lineageTag: 90c1f2cf-c433-4271-aeb7-5fccc7b04ce1

			measure FCOLOR = FCOLOR ( [Sales Amount] )
				lineageTag: 0a9b5668-731f-46ac-8c10-74525dba1fd8

			measure FVERSION = FVERSION ( "v8.10/18/2025" )
				lineageTag: 961ed2a8-33e1-4547-bccb-7a35a788353c

			measure FLASTREFRESHDATE = FLASTREFRESHDATE ( UTCNOW () )
				formatString: General Date
				lineageTag: e462ec65-6845-4bcb-a88c-daef964e62a4

			measure FMAXX = FMAXX ( [Sales Amount] )
				formatString: #,0
				lineageTag: d5fbf6e6-9d6d-4745-bbd7-c2a3e4a45023

			column Value
				isHidden
				lineageTag: 88e202b2-0027-43a5-bb02-4108de5434c3
				summarizeBy: none
				isNameInferred
				sourceColumn: [Value]

				annotation SummarizationSetBy = Automatic

			partition DAX = calculated
				mode: import
				source = ```
						
						    { "" }
						```

			annotation PBI_Id = 246adfa278d945b2aa3c7202853e0692

		relationship AutoDetected_67e5a7b1-0dc1-4e98-aa2d-4a4d3ae69e0c
			fromColumn: Sales.CustomerKey
			toColumn: Customer.CustomerKey

		relationship AutoDetected_546eb3e3-969d-4f36-aac1-ce15980f2aac
			fromColumn: Sales.StoreKey
			toColumn: Store.StoreKey

		relationship AutoDetected_3963eabf-3afb-458d-b0fd-0ad281333454
			fromColumn: Sales.ProductKey
			toColumn: Product.ProductKey

		relationship 4afac84a-954c-edfa-5f91-7ef2a2082787
			fromColumn: Sales.'Order Date'
			toColumn: Date.Date

		cultureInfo en-US

			linguisticMetadata = {"Version":"1.0.0","Language":"en-US"}
				contentType: json

		function FMAXX =
				(_measure: expr) =>
						VAR CY = _measure
						VAR Result = MAXX(
							ALLSELECTED('Product'[Brand]),
							_measure
						) - _measure
						RETURN
							Result
			lineageTag: a551452b-87c1-440a-9159-4cbf7bfce49e

		function FPY =
				(_measure: expr) =>
						VAR CY = _measure
						VAR Result = CALCULATE(
							_measure,
							DATEADD(
								'Date'[Date],
								-1,
								YEAR
							)
						)
						RETURN
							Result
			lineageTag: ee82a8d5-f088-4a57-9b75-7ff04459d6ad

		function FYOYD =
				(_measure: expr) =>
						VAR CY = _measure
						VAR PY = CALCULATE(
							_measure,
							DATEADD(
								'Date'[Date],
								-1,
								YEAR
							)
						)
						VAR Result = CY - PY
						RETURN
							Result
			lineageTag: fcc0cd27-11d7-424e-9d92-77c842401ebc

		function FCOLOR =
				(_measure: expr) =>
						VAR CY = _measure
						VAR PY = CALCULATE(
							_measure,
							DATEADD(
								'Date'[Date],
								-1,
								YEAR
							)
						)
						VAR Result = DIVIDE(
							_measure,
							PY
						) - 1
						RETURN
							SWITCH(
								TRUE(),
								Result > 0, "Lime",
								Result < 0, "Orange",
								BLANK()
							)
			lineageTag: 124022bd-7927-4173-a91a-d43bd2c9373d

		function FYOY =
				(_measure: expr) =>
						VAR CY = _measure
						VAR PY = CALCULATE(
							_measure,
							DATEADD(
								'Date'[Date],
								-1,
								YEAR
							)
						)
						VAR Result = CY - PY
						RETURN
							Result
			lineageTag: bafcc048-0342-4d72-a1dd-d927cb7035d5

		function FLASTREFRESHDATE =
				(_measure: expr) =>
						VAR FTIME = TIME(
							2,
							0,
							0
						)
						VAR Result = _measure + FTIME
						RETURN
							Result
			lineageTag: ab1dc766-05c8-4080-9cda-1f0a059c9a85

		function FREFLINE1 = (A) => A
			lineageTag: c8e016e9-fd6f-4bd3-bad5-9d746f827e69

		function FREFLINE2 = (A) => A
			lineageTag: 62688ba6-3002-490d-b223-52c4330cad01

		function FREFLINE3 = (A) => A
			lineageTag: c1fe9ac8-1729-458b-8d34-c88434499233

		function FREFLINE4 = (A) => A
			lineageTag: d6a15eb8-f591-481e-8515-51862e000d44

		function FREFLINE5 = (A) => A
			lineageTag: 46d06e37-56f0-459e-b81d-f77a14b0d45d

		function FVERSION = (A) => A
			lineageTag: cc51fc53-bdcf-449f-a7e0-3f26cafd9059

		function FLOWERBOUND = (A) => A
			lineageTag: d5ba37f8-b92a-41c4-ac5b-9efee52063f7

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["Currency Exchange","Customer","Date","Sales","Store","Product"]

		annotation PBI_ProTooling = ["DaxQueryView_Desktop","TMDLView_Desktop"]

		annotation __TEdtr = 1

