createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table Sales
			lineageTag: f46bdf08-be04-4c0e-b4d2-96da0d9643aa

			column Date
				formatString: General Date
				lineageTag: a8bbb8f0-4b58-4f1f-bf19-52a9d8b61f1c
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

			column Value
				formatString: 0
				lineageTag: 55e8f02a-56d7-4657-8e5d-5b28ab5531c6
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Value]

				annotation SummarizationSetBy = Automatic

			column ID_Segment
				formatString: 0
				lineageTag: d457a6c0-c3c2-4f21-aeed-6e60627c0627
				summarizeBy: none
				isNameInferred
				sourceColumn: [ID_Segment]

				annotation SummarizationSetBy = Automatic

			column ID_Country
				formatString: 0
				lineageTag: 88dbd19a-175c-4653-a17b-4b11d2d5ec2a
				summarizeBy: none
				isNameInferred
				sourceColumn: [ID_Country]

				annotation SummarizationSetBy = Automatic

			column ID_Product
				formatString: 0
				lineageTag: 36c0221e-49a7-4ed4-91af-514cfa7c702f
				summarizeBy: none
				isNameInferred
				sourceColumn: [ID_Product]

				annotation SummarizationSetBy = Automatic

			column Sales
				formatString: 0
				lineageTag: 92c51778-8805-458f-af2c-0446c67d94aa
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Sales]

				annotation SummarizationSetBy = Automatic

			column COGS
				formatString: 0
				lineageTag: 6adc2206-6c95-4412-8741-f67af2fff8c4
				summarizeBy: sum
				isNameInferred
				sourceColumn: [COGS]

				annotation SummarizationSetBy = Automatic

			partition Sales = calculated
				mode: import
				source = ```
						
						// Generate a sample Sales table with random data
						VAR Result = 
						    ADDCOLUMNS(
						        // Generate a base table with 50000 rows (values from 1 to 50000)
						        GENERATESERIES(1, 50000),
						
						        // Add a random date between today and 700 days ago
						        "Date", TODAY() - RANDBETWEEN(1, 700),
						
						        // Add a random segment ID (values between 1 and 5)
						        "ID_Segment", RANDBETWEEN(1, 5),
						
						        // Add a random country ID (values between 1 and 5)
						        "ID_Country", RANDBETWEEN(1, 5),
						
						        // Add a random product ID (values between 1 and 6)
						        "ID_Product", RANDBETWEEN(1, 6)
						    )
						
						// Add Sales and COGS values to the result table and return it
						RETURN
						    ADDCOLUMNS(
						        Result,
						
						        // Add a random Sales value between 10 and 45
						        "Sales", RANDBETWEEN(100, 450),
						
						        // Add a random COGS (Cost of Goods Sold) value between 5 and 15
						        "COGS", RANDBETWEEN(50, 150)
						    )
						
						```

			annotation PBI_Id = d283c66d4c904141b1f98c5d9e64465d

		table DimSegment
			lineageTag: 3dc89ce2-5954-4966-a2ca-088bccf0a0e7

			column Segment
				dataType: string
				lineageTag: 57a29cc8-75c9-4c21-98e4-5fdf8999e916
				summarizeBy: none
				sourceColumn: Segment

				annotation SummarizationSetBy = Automatic

			column ID_Segment
				dataType: int64
				formatString: 0
				lineageTag: 82671398-86bb-4008-8e1f-9e56eb8d769a
				summarizeBy: none
				sourceColumn: ID_Segment

				annotation SummarizationSetBy = Automatic

			partition DimSegment = m
				mode: import
				source = ```
						let
						    // Step 1: Decompress and parse the Base64-encoded JSON data into a table
						    Source = Table.FromRows(
						        Json.Document(
						            Binary.Decompress(
						                Binary.FromText(
						                    "HcpNCoAgEEDhq8is3fR3gSJaBUFLcSE0kKRTzFjnT91+7xkDy/0hU0RKoKEBqw2s/oiOLyzSVplOR4RBbY4TIUsOXQ0zJeSHvWCmvtIeXQhqfMUTSjkHsPYH", 
						                    BinaryEncoding.Base64
						                ), 
						                Compression.Deflate
						            )
						        ), 
						        // Define the column types after decompression (both as nullable text initially)
						        let _t = ((type nullable text) meta [Serialized.Text = true]) 
						        in type table [Segment = _t, ID_Segment = _t]
						    ),
						
						    // Step 2: Change column types to appropriate types
						    // "Segment" -> text
						    // "ID_Segment" -> 64-bit integer
						    #"Changed Type" = Table.TransformColumnTypes(
						        Source,
						        {{"Segment", type text}, {"ID_Segment", Int64.Type}}
						    )
						
						in
						    // Output the final transformed table
						    #"Changed Type"
						```

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table DimCountry
			lineageTag: d302a70b-52fd-4d8a-93cd-06bad00ca483

			column Country
				dataType: string
				lineageTag: afdc2b06-98c2-4f44-88dc-cb1a2967012b
				summarizeBy: none
				sourceColumn: Country

				annotation SummarizationSetBy = Automatic

			column ID_Country
				dataType: int64
				formatString: 0
				lineageTag: ca4b5ae5-a646-40c4-a0cf-64127e1854bc
				summarizeBy: none
				sourceColumn: ID_Country

				annotation SummarizationSetBy = Automatic

			partition DimCountry = m
				mode: import
				source = ```
						let
						    // Step 1: Decode and decompress the Base64 string, then convert the JSON to a table
						    Source = Table.FromRows(
						        Json.Document(
						            Binary.Decompress(
						                Binary.FromText(
						                    "i45Wck7MS0xJVNJRMlSK1YlWck8tyk3MqwTyjcB8t6LEvORUINcYzPVNrchMzgdyTcDc0GBHINtUKTYWAA==", 
						                    BinaryEncoding.Base64
						                ), 
						                Compression.Deflate
						            )
						        ),
						        // Define the column types (both as nullable text initially)
						        let _t = ((type nullable text) meta [Serialized.Text = true]) 
						        in type table [Country = _t, ID_Country = _t]
						    ),
						
						    // Step 2: Convert column types to appropriate types
						    // "Country" -> text
						    // "ID_Country" -> 64-bit integer
						    #"Changed Type" = Table.TransformColumnTypes(
						        Source,
						        {{"Country", type text}, {"ID_Country", Int64.Type}}
						    )
						
						in
						    // Output the final transformed table
						    #"Changed Type"
						```

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table DimProduct
			lineageTag: 475029f6-f0ef-467e-8446-9ff047293c47

			column Product
				dataType: string
				lineageTag: cad67ffc-8c08-45be-8303-ca2a639d49ed
				summarizeBy: none
				sourceColumn: Product

				annotation SummarizationSetBy = Automatic

			column ID_Product
				dataType: int64
				formatString: 0
				lineageTag: 34dcd8b4-73cc-4881-a7d1-d6a257dbb198
				summarizeBy: none
				sourceColumn: ID_Product

				annotation SummarizationSetBy = Automatic

			partition DimProduct = m
				mode: import
				source = ```
						let
						    // Step 1: Decode and decompress the Base64-encoded, compressed binary data
						    // Then parse the resulting JSON into a table structure
						    Source = Table.FromRows(
						        Json.Document(
						            Binary.Decompress(
						                Binary.FromText(
						                    "i45Wck4sKkotSS1KVNJRMlSK1YlW8s3PK0nMA/GNwPyAxOLUfCDPGMwLS80BcUwgnJAQINsUzHbMTSzKzMkB6TNTio0FAA==", 
						                    BinaryEncoding.Base64
						                ), 
						                Compression.Deflate
						            )
						        ),
						        // Define the table type using nullable text for both columns initially
						        let _t = ((type nullable text) meta [Serialized.Text = true]) 
						        in type table [Product = _t, ID_Product = _t]
						    ),
						
						    // Step 2: Change column data types to appropriate types
						    // "Product" -> text
						    // "ID_Product" -> 64-bit integer
						    #"Changed Type" = Table.TransformColumnTypes(
						        Source,
						        {{"Product", type text}, {"ID_Product", Int64.Type}}
						    )
						
						in
						    // Return the final transformed table
						    #"Changed Type"
						```

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table Date
			lineageTag: 58d47fea-a8bc-4ecc-b3ed-a11821db5341
			dataCategory: Time

			column Date
				isKey
				formatString: mm/dd/yyyy
				lineageTag: f7075d55-1928-41b7-a9f2-238869931aeb
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Year
				formatString: 0
				lineageTag: 35bd2ed8-f3e6-4a12-9eeb-f801bb4d156b
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year]

				annotation SummarizationSetBy = Automatic

			column 'Year Month'
				lineageTag: 5c4d5105-113c-4392-90a8-a4f9e790614a
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year Month]
				sortByColumn: 'Year Month Order'

				annotation SummarizationSetBy = Automatic

			column 'Year Month Order'
				lineageTag: d4f017fd-9173-4745-853a-630df906d71e
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year Month Order]

				annotation SummarizationSetBy = Automatic

			column Quarter
				lineageTag: ac486492-dd23-4c0a-90fe-69c4661a2517
				summarizeBy: none
				isNameInferred
				sourceColumn: [Quarter]

				annotation SummarizationSetBy = Automatic

			column Month
				lineageTag: db4149d5-62d0-4027-ba50-faf840829077
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month]
				sortByColumn: 'Month Number'

				annotation SummarizationSetBy = Automatic

			column 'Month Number'
				formatString: 0
				lineageTag: fcdf4610-7783-485b-8758-5e4cc02d71fc
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month Number]

				annotation SummarizationSetBy = Automatic

			hierarchy 'Date Hierarchy'
				lineageTag: 876d6db5-92a1-4ab5-a13e-3e41fdda7c54

				level Year
					lineageTag: 38cf797e-5855-4901-a52b-a0fe53d9b56b
					column: Year

				level Quarter
					lineageTag: b026f174-c9a3-46a3-8cc4-231d3cf9ef87
					column: Quarter

				level Month
					lineageTag: 68b2b010-4159-44e4-9244-e2c3da6895a8
					column: Month

				level Date
					lineageTag: 35a68a5c-b8a7-4980-80d8-a28f74358d3e
					column: Date

			partition Date = calculated
				mode: import
				source = ```
						
						VAR __startdate = 
						    // Get the first non-blank Sales[Date] where [Sales] has values
						    FIRSTNONBLANK('Sales'[Date], [Sales])
						
						VAR __enddate = 
						    // Get the last non-blank Sales[Date] where [Sales] has values
						    LASTNONBLANK('Sales'[Date], [Sales])
						
						VAR Result = 
						    // Create a calculated table using CALENDAR function from start to end date
						    ADDCOLUMNS(
						        CALENDAR(__startdate, __enddate),
						        
						        // Add "Year" column
						        "Year", YEAR([Date]),
						
						        // Add formatted Year-Month (e.g., "2023-Jan")
						        "Year Month", FORMAT([Date], "yyyy-mmm"),
						
						        // Add sortable YearMonth format (e.g., "202301")
						        "Year Month Order", FORMAT([Date], "yyyymm"),
						
						        // Add Quarter in format "Q1", "Q2", etc.
						        "Quarter", "Q" & QUARTER([Date]),
						
						        // Add abbreviated month name (e.g., "Jan")
						        "Month", FORMAT([Date], "mmm"),
						
						        // Add numeric month value (1–12)
						        "Month Number", MONTH([Date])
						    )
						
						RETURN
						    Result
						
						```

			annotation PBI_Id = ee0048671a434aa582efe3d201e2497b

		table DAX
			lineageTag: 7d468fd2-829e-4cfd-938c-4fdb43dbdfdd

			measure Sales =
					
					// Calculate the total (sum) of the [Sales] column in the Sales table
					SUM ( 'Sales'[Sales] )
				formatString: \$#,0;(\$#,0);\$#,0
				lineageTag: 95b13e45-b786-46bb-b6eb-b21403f22f25

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure 'Report Criteria' =
					
					// Create a report criteria string by combining selected values for country, discount segment, and date
					VAR __country =
					    SELECTEDVALUE ( DimCountry[Country] ) // Get the selected country from the DimCountry table
					VAR __discount =
					    SELECTEDVALUE ( DimSegment[Segment] ) // Get the selected segment from the DimSegment table
					VAR __date =
					    SELECTEDVALUE ( 'Date'[Year] ) // Get the selected Year from the Date table
					// Combine the selected values into a single string result
					VAR Result = __country & ", " & __discount & ", " & __date // Concatenate country, discount, and date values
					// Return the combined result
					RETURN
					    "Quick summary" & UNICHAR ( 10 ) & Result
				lineageTag: 12e7dbd0-2f23-4933-ad98-e051096d7ece

			measure COGS =
					
					// Calculate the Total Cost of Goods Sold (COGS)
					SUM ( Sales[COGS] )
					// Sum the values in the 'COGS' column of the 'Sales' table
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 5fd19a27-f705-4915-a268-5a9f572cc958

			measure Profit =
					
					// Calculate the Profit by subtracting COGS from Sales
					[Sales] - [COGS]
					// Subtract the calculated COGS measure from the Sales measure
				formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
				lineageTag: 4942789f-e5a6-483a-b447-11954cefb813

			measure 'Sales by Product' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
					VAR Result =
					    SWITCH ( TRUE (), [Sales] = __max, "Green", [Sales] = __min, "Red", "#061953" )
					RETURN
					    Result
				lineageTag: 61a828f0-9c27-442e-8164-cebfd40a880e

			measure 'COGS by Product' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
					VAR Result =
					    SWITCH ( TRUE (), [COGS] = __max, "Red", [COGS] = __min, "Green", "#061953" )
					RETURN
					    Result
				lineageTag: ac9712db-1622-4d86-b4dc-c148dc101a33

			measure 'Profit by Product' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
					VAR Result =
					    SWITCH (
					        TRUE (),
					        [Profit] = __max, "Green",
					        [Profit] = __min, "Red",
					        "#061953"
					    )
					RETURN
					    Result
				lineageTag: e5ed3103-0105-49a6-b613-d1afbcd25b44

			measure 'COGS by Product (txt)' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
					VAR Result =
					    SWITCH (
					        TRUE (),
					        [COGS] = __max, "#605E5C",
					        [COGS] = __min, "#605E5C",
					        "#FFFFFF00"
					    )
					RETURN
					    Result
				lineageTag: 68fd26aa-3c57-4cd8-8960-41df0ab46994

			measure 'Sales by Product (txt)' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
					VAR Result =
					    SWITCH (
					        TRUE (),
					        [Sales] = __max, "#605E5C",
					        [Sales] = __min, "#605E5C",
					        "#FFFFFF00"
					    )
					RETURN
					    Result
				lineageTag: 52138b28-7416-4aee-a771-bccebab40ee0

			measure 'Profit by Product (txt)' =
					
					VAR __min =
					    MINX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
					VAR __max =
					    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
					VAR Result =
					    SWITCH (
					        TRUE (),
					        [Profit] = __max, "#605E5C",
					        [Profit] = __min, "#605E5C",
					        "#FFFFFF00"
					    )
					RETURN
					    Result
				lineageTag: b87f566b-83ca-4fe8-b847-baf179038c98

			measure 'Sales Average' =
					
					CALCULATE ( AVERAGEX ( DimProduct, [Sales] ), ALLSELECTED () )
				lineageTag: 48d14fe7-07ee-41e5-95ef-13339798e355

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'COGS Average' =
					
					CALCULATE ( AVERAGEX ( DimProduct, [COGS] ), ALLSELECTED () )
				lineageTag: c1345d5a-eafe-46e7-9b94-85cdc6c6075c

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Profit Average' =
					
					CALCULATE ( AVERAGEX ( DimProduct, [Profit] ), ALLSELECTED () )
				lineageTag: 6d3d8dc7-ec9a-4b81-b854-0906b5991638

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Sales Average (yyyy-mm)' =
					
					CALCULATE (
					    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [Sales] ),
					    ALLSELECTED ()
					)
				lineageTag: c9c9c1bd-77df-4f3e-a28b-338280e7c73f

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'COGS Average (yyyy-mm)' =
					
					CALCULATE (
					    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [COGS] ),
					    ALLSELECTED ()
					)
				lineageTag: 03a09135-1589-4d20-b714-0ac32d46b675

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Profit Average (yyyy-mm)' =
					
					CALCULATE (
					    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [Profit] ),
					    ALLSELECTED ()
					)
				lineageTag: 95591961-961d-4920-a964-def36981345e

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Value
				isHidden
				lineageTag: 95c16aea-39aa-4608-95f9-82bfdf688a2a
				summarizeBy: none
				isNameInferred
				sourceColumn: [Value]

				annotation SummarizationSetBy = Automatic

			partition DAX = calculated
				mode: import
				source = ```
						
						{
						    // A single row table with one column (no name assigned) and one empty string value
						    ""
						}
						
						```

			annotation PBI_Id = 883e31ddacaa4275a2a895b954edf633

		relationship f38a9eed-50b0-dd5d-4264-f8498c014866
			fromColumn: Sales.Date
			toColumn: Date.Date

		relationship e2c68397-7ded-9218-2a18-6e4a4a0792d3
			fromColumn: Sales.ID_Segment
			toColumn: DimSegment.ID_Segment

		relationship 70b7e544-3395-ebd1-8775-1804ca612549
			fromColumn: Sales.ID_Country
			toColumn: DimCountry.ID_Country

		relationship 6bb01599-7713-f161-90e2-70a07cb5d712
			fromColumn: Sales.ID_Product
			toColumn: DimProduct.ID_Product

		cultureInfo en-US

			linguisticMetadata = {"Version":"4.1.0","Language":"en-US","Entities":{"sale":{"Definition":{"Binding":{"ConceptualEntity":"Sales"}},"State":"Generated","Terms":[{"sale":{"State":"Generated","Weight":0.87}},{"auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.date":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"SemanticType":"Time"},"sale.value":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"Value"}},"State":"Generated","Terms":[{"value":{"State":"Generated"}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"sale.ID_segment":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"ID_Segment"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ID segment":{"State":"Generated"}},{"ID_Segment":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id bit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id fragment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sale.ID_country":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"ID_Country"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ID country":{"State":"Generated"}},{"ID_Country":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"identification country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identity country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identifier country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"credential country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"sale.ID_product":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"ID_Product"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ID product":{"State":"Generated"}},{"ID_Product":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"identification product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identity product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identifier product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"credential product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"sale.sale":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"Sales"}},"State":"Generated","Terms":[{"sale":{"State":"Generated"}},{"auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"sale.cog":{"Definition":{"Binding":{"ConceptualEntity":"Sales","ConceptualProperty":"COGS"}},"State":"Generated","Terms":[{"cog":{"State":"Generated"}},{"mechanism":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"cogwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"gearwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"flywheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"component":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"gear":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"wheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"dim_segment":{"Definition":{"Binding":{"ConceptualEntity":"DimSegment"}},"State":"Generated","Terms":[{"dim segment":{"State":"Generated"}},{"DimSegment":{"Type":"Noun","State":"Generated","Weight":0.99}},{"dim division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dim subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dim section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim bit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim fragment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"dim_segment.segment":{"Definition":{"Binding":{"ConceptualEntity":"DimSegment","ConceptualProperty":"Segment"}},"State":"Generated","Terms":[{"segment":{"State":"Generated"}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"bit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"fragment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"dim_segment.ID_segment":{"Definition":{"Binding":{"ConceptualEntity":"DimSegment","ConceptualProperty":"ID_Segment"}},"State":"Generated","Terms":[{"ID segment":{"State":"Generated"}},{"ID_Segment":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id section":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id sector":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id bit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id fragment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"dim_country":{"Definition":{"Binding":{"ConceptualEntity":"DimCountry"}},"State":"Generated","Terms":[{"dim country":{"State":"Generated"}},{"DimCountry":{"Type":"Noun","State":"Generated","Weight":0.99}},{"dim nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dim location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}}]},"dim_country.country":{"Definition":{"Binding":{"ConceptualEntity":"DimCountry","ConceptualProperty":"Country"}},"State":"Generated","Terms":[{"country":{"State":"Generated"}},{"nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"dim_country.ID_country":{"Definition":{"Binding":{"ConceptualEntity":"DimCountry","ConceptualProperty":"ID_Country"}},"State":"Generated","Terms":[{"ID country":{"State":"Generated"}},{"ID_Country":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id nation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"identification country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identity country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identifier country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"credential country":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"dim_product":{"Definition":{"Binding":{"ConceptualEntity":"DimProduct"}},"State":"Generated","Terms":[{"dim product":{"State":"Generated"}},{"DimProduct":{"Type":"Noun","State":"Generated","Weight":0.99}},{"dim artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"dim item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"dim produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"dim_product.product":{"Definition":{"Binding":{"ConceptualEntity":"DimProduct","ConceptualProperty":"Product"}},"State":"Generated","Terms":[{"product":{"State":"Generated"}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"dim_product.ID_product":{"Definition":{"Binding":{"ConceptualEntity":"DimProduct","ConceptualProperty":"ID_Product"}},"State":"Generated","Terms":[{"ID product":{"State":"Generated"}},{"ID_Product":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"identification product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identity product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identifier product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"credential product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"date":{"Definition":{"Binding":{"ConceptualEntity":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated","Weight":0.87}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"date.date":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"SemanticType":"Time"},"date.year":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Year"}},"State":"Generated","Terms":[{"year":{"State":"Generated"}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"date.year_month":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Year Month"}},"State":"Generated","Terms":[{"year month":{"State":"Generated"}},{"year mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"yr month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"date.year_month_order":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Year Month Order"}},"State":"Generated","Terms":[{"year month order":{"State":"Generated"}},{"order":{"State":"Generated","Weight":0.97}},{"month order":{"State":"Generated","Weight":0.97}},{"yr month order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"year mth order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"year month instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"year month direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"year month edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"month instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"month direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"month edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"year month command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"date.quarter":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Quarter"}},"State":"Generated","Terms":[{"quarter":{"State":"Generated"}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}}]},"date.month":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Month"}},"State":"Generated","Terms":[{"month":{"State":"Generated"}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"date.month_number":{"Definition":{"Binding":{"ConceptualEntity":"Date","ConceptualProperty":"Month Number"}},"State":"Generated","Terms":[{"month number":{"State":"Generated"}},{"month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"date.date_hierarchy":{"Definition":{"Binding":{"ConceptualEntity":"Date","Hierarchy":"Date Hierarchy"}},"State":"Generated","Terms":[{"date hierarchy":{"State":"Generated"}},{"hierarchy":{"State":"Generated","Weight":0.97}},{"moment hierarchy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period hierarchy":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"date ladder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"date grading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"date order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"date pyramid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ladder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"grading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"pyramid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}],"SemanticType":"Time"},"date.date_hierarchy.year":{"Definition":{"Binding":{"ConceptualEntity":"Date","Hierarchy":"Date Hierarchy","HierarchyLevel":"Year"}},"State":"Generated","Terms":[{"year":{"State":"Generated"}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"date.date_hierarchy.quarter":{"Definition":{"Binding":{"ConceptualEntity":"Date","Hierarchy":"Date Hierarchy","HierarchyLevel":"Quarter"}},"State":"Generated","Terms":[{"quarter":{"State":"Generated"}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}}],"SemanticType":"Time"},"date.date_hierarchy.month":{"Definition":{"Binding":{"ConceptualEntity":"Date","Hierarchy":"Date Hierarchy","HierarchyLevel":"Month"}},"State":"Generated","Terms":[{"month":{"State":"Generated"}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"date.date_hierarchy.date":{"Definition":{"Binding":{"ConceptualEntity":"Date","Hierarchy":"Date Hierarchy","HierarchyLevel":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"SemanticType":"Time"},"dax":{"Definition":{"Binding":{"ConceptualEntity":"DAX"}},"State":"Generated","Terms":[{"dax":{"State":"Generated"}}]},"dax.value":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Value"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"value":{"State":"Generated"}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"dax.sale":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Sales"}},"State":"Generated","Terms":[{"sale":{"State":"Generated"}},{"auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"dax.report_criteria":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Report Criteria"}},"State":"Generated","Terms":[{"report criteria":{"State":"Generated"}},{"criteria":{"State":"Generated","Weight":0.97}},{"information criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"commentary criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"description criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"presentation criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"statement criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"forecast criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"account criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"article criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"narrative criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"paper criterion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"dax.cog":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"COGS"}},"State":"Generated","Terms":[{"cog":{"State":"Generated"}},{"mechanism":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"cogwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"gearwheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"flywheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"component":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"gear":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"wheel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"dax.profit":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Profit"}},"State":"Generated","Terms":[{"profit":{"State":"Generated"}},{"income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"revenue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"return":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"advantage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"gain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"benefit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"use":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"reward":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"dax.sales_by_product":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Sales by Product"}},"State":"Generated","Terms":[{"sales by product":{"State":"Generated"}},{"sales":{"State":"Generated","Weight":0.97}},{"sale by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sale by artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"sale by item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"sale by merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"sale by produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"dax.COGS_by_product":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"COGS by Product"}},"State":"Generated","Terms":[{"COGS by product":{"State":"Generated"}},{"COGS":{"State":"Generated","Weight":0.97}},{"cog by artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"cog by item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"cog by merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"cog by produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"mechanism by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"device by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"workings by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"works by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"mechanism":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"device":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"dax.profit_by_product":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Profit by Product"}},"State":"Generated","Terms":[{"profit by product":{"State":"Generated"}},{"profit by artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"profit by item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"profit by merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"profit by produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"income by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"revenue by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"turnover by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"return by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"yield by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"advantage by product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"dax.COGS_by_product_txt":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"COGS by Product (txt)"}},"State":"Generated","Terms":[{"COGS by product (txt)":{"State":"Generated"}},{"COGS by product":{"State":"Generated","Weight":0.75}}]},"dax.sales_by_product_txt":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Sales by Product (txt)"}},"State":"Generated","Terms":[{"sales by product (txt)":{"State":"Generated"}},{"sales by product":{"State":"Generated","Weight":0.75}}]},"dax.profit_by_product_txt":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Profit by Product (txt)"}},"State":"Generated","Terms":[{"profit by product (txt)":{"State":"Generated"}},{"profit by product":{"State":"Generated","Weight":0.75}}]},"dax.sales_average":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Sales Average"}},"State":"Generated","Terms":[{"sales average":{"State":"Generated"}},{"sale average":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"sale mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"sale norm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"sale mean":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"sale median":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"dax.COGS_average":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"COGS Average"}},"State":"Generated","Terms":[{"COGS average":{"State":"Generated"}},{"cog mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"cog norm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"cog mean":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"cog median":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"dax.profit_average":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Profit Average"}},"State":"Generated","Terms":[{"profit average":{"State":"Generated"}},{"profit mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"profit norm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"profit mean":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"profit median":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"dax.sales_average_yyyymm":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Sales Average (yyyy-mm)"}},"State":"Generated","Terms":[{"sales average (yyyy-mm)":{"State":"Generated"}},{"sales average":{"State":"Generated","Weight":0.75}},{"sales average (yyyy mm)":{"State":"Generated","Weight":0.97}}]},"dax.COGS_average_yyyymm":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"COGS Average (yyyy-mm)"}},"State":"Generated","Terms":[{"COGS average (yyyy-mm)":{"State":"Generated"}},{"COGS average":{"State":"Generated","Weight":0.75}},{"COGS average (yyyy mm)":{"State":"Generated","Weight":0.97}},{"Average":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"dax.profit_average_yyyymm":{"Definition":{"Binding":{"ConceptualEntity":"DAX","ConceptualProperty":"Profit Average (yyyy-mm)"}},"State":"Generated","Terms":[{"profit average (yyyy-mm)":{"State":"Generated"}},{"profit average":{"State":"Generated","Weight":0.75}},{"profit average (yyyy mm)":{"State":"Generated","Weight":0.97}}]}},"Relationships":{"dax_cogs_by_COGS_by_product":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.COGS_by_product":{"Target":{"Entity":"dax.COGS_by_product"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"dax"},"Verbs":[{"COG":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"by":{"State":"Generated"}}],"Object":{"Role":"dax.COGS_by_product"}}]},"State":"Generated","Weight":0.95,"ID":"dax_COG_by_COGS_by_product"},{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.COGS_by_product"}},"State":"Generated","Weight":0.99,"ID":"dax_have_COGS_by_product"}]},"dax_profits_by_profit_by_product":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.profit_by_product":{"Target":{"Entity":"dax.profit_by_product"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"dax"},"Verbs":[{"profit":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"by":{"State":"Generated"}}],"Object":{"Role":"dax.profit_by_product"}}]},"State":"Generated","Weight":0.95,"ID":"dax_profit_by_profit_by_product"},{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.profit_by_product"}},"State":"Generated","Weight":0.99,"ID":"dax_have_profit_by_product"}]},"dax_cogs_by_COGS_by_product_txt":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.COGS_by_product_txt":{"Target":{"Entity":"dax.COGS_by_product_txt"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"dax"},"Verbs":[{"COG":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"by":{"State":"Generated"}}],"Object":{"Role":"dax.COGS_by_product_txt"}}]},"State":"Generated","Weight":0.95,"ID":"dax_COG_by_COGS_by_product_txt"},{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.COGS_by_product_txt"}},"State":"Generated","Weight":0.99,"ID":"dax_have_COGS_by_product_txt"}]},"dax_profits_by_profit_by_product_txt":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.profit_by_product_txt":{"Target":{"Entity":"dax.profit_by_product_txt"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"dax"},"Verbs":[{"profit":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"by":{"State":"Generated"}}],"Object":{"Role":"dax.profit_by_product_txt"}}]},"State":"Generated","Weight":0.95,"ID":"dax_profit_by_profit_by_product_txt"},{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.profit_by_product_txt"}},"State":"Generated","Weight":0.99,"ID":"dax_have_profit_by_product_txt"}]},"dim_country_in_country":{"Binding":{"ConceptualEntity":"DimCountry"},"State":"Generated","Roles":{"dim_country":{"Target":{"Entity":"dim_country"}},"dim_country.country":{"Target":{"Entity":"dim_country.country"}}},"SemanticSlots":{"Where":{"Role":"dim_country.country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"dim_country"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"dim_country.country"}},"State":"Generated","Weight":0.99,"ID":"dim_countries_are_in_countries"}]},"sale_in_dim_country":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dim_country":{"Target":{"Entity":"dim_country"}}},"SemanticSlots":{"Where":{"Role":"dim_country"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"sale"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"dim_country"}},"State":"Generated","Weight":0.99,"ID":"sales_are_in_dim_countries"}]},"sale_has_date":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.date":{"Target":{"Entity":"sale.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.date"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dates"}]},"sale_has_value":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.value":{"Target":{"Entity":"sale.value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.value"}},"State":"Generated","Weight":0.99,"ID":"sales_have_values"}]},"sale_has_sale":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.sale":{"Target":{"Entity":"sale.sale"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.sale"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sales"}]},"sale_has_cog":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"sale.cog":{"Target":{"Entity":"sale.cog"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"sale.cog"}},"State":"Generated","Weight":0.99,"ID":"sales_have_cogs"}]},"dim_segment_has_segment":{"Binding":{"ConceptualEntity":"DimSegment"},"State":"Generated","Roles":{"dim_segment":{"Target":{"Entity":"dim_segment"}},"dim_segment.segment":{"Target":{"Entity":"dim_segment.segment"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_segment"},"Object":{"Role":"dim_segment.segment"}},"State":"Generated","Weight":0.99,"ID":"dim_segments_have_segments"}]},"dim_segment_has_ID_segment":{"Binding":{"ConceptualEntity":"DimSegment"},"State":"Generated","Roles":{"dim_segment":{"Target":{"Entity":"dim_segment"}},"dim_segment.ID_segment":{"Target":{"Entity":"dim_segment.ID_segment"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_segment"},"Object":{"Role":"dim_segment.ID_segment"}},"State":"Generated","Weight":0.99,"ID":"dim_segments_have_ID_segments"}]},"dim_country_has_country":{"Binding":{"ConceptualEntity":"DimCountry"},"State":"Generated","Roles":{"dim_country":{"Target":{"Entity":"dim_country"}},"dim_country.country":{"Target":{"Entity":"dim_country.country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_country"},"Object":{"Role":"dim_country.country"}},"State":"Generated","Weight":0.99,"ID":"dim_countries_have_countries"}]},"dim_country_has_ID_country":{"Binding":{"ConceptualEntity":"DimCountry"},"State":"Generated","Roles":{"dim_country":{"Target":{"Entity":"dim_country"}},"dim_country.ID_country":{"Target":{"Entity":"dim_country.ID_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_country"},"Object":{"Role":"dim_country.ID_country"}},"State":"Generated","Weight":0.99,"ID":"dim_countries_have_ID_countries"}]},"dim_product_has_product":{"Binding":{"ConceptualEntity":"DimProduct"},"State":"Generated","Roles":{"dim_product":{"Target":{"Entity":"dim_product"}},"dim_product.product":{"Target":{"Entity":"dim_product.product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"dim_product.product"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_products"}]},"dim_product_has_ID_product":{"Binding":{"ConceptualEntity":"DimProduct"},"State":"Generated","Roles":{"dim_product":{"Target":{"Entity":"dim_product"}},"dim_product.ID_product":{"Target":{"Entity":"dim_product.ID_product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"dim_product.ID_product"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_ID_products"}]},"date_has_date":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.date":{"Target":{"Entity":"date.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.date"}},"State":"Generated","Weight":0.99,"ID":"dates_have_dates"}]},"date_has_year":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.year":{"Target":{"Entity":"date.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.year"}},"State":"Generated","Weight":0.99,"ID":"dates_have_years"}]},"date_has_year_month":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.year_month":{"Target":{"Entity":"date.year_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.year_month"}},"State":"Generated","Weight":0.99,"ID":"dates_have_year_months"}]},"date_has_year_month_order":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.year_month_order":{"Target":{"Entity":"date.year_month_order"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.year_month_order"}},"State":"Generated","Weight":0.99,"ID":"dates_have_year_month_orders"}]},"date_has_quarter":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.quarter":{"Target":{"Entity":"date.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.quarter"}},"State":"Generated","Weight":0.99,"ID":"dates_have_quarters"}]},"date_has_month":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.month":{"Target":{"Entity":"date.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.month"}},"State":"Generated","Weight":0.99,"ID":"dates_have_months"}]},"date_has_month_number":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.month_number":{"Target":{"Entity":"date.month_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.month_number"}},"State":"Generated","Weight":0.99,"ID":"dates_have_month_numbers"}]},"date_has_date_hierarchy":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date":{"Target":{"Entity":"date"}},"date.date_hierarchy":{"Target":{"Entity":"date.date_hierarchy"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"date.date_hierarchy"}},"State":"Generated","Weight":0.99,"ID":"dates_have_date_hierarchies"}]},"sale_has_dax_sale":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.sale":{"Target":{"Entity":"dax.sale"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.sale"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sale"}]},"dax_has_report_criteria":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.report_criteria":{"Target":{"Entity":"dax.report_criteria"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.report_criteria"}},"State":"Generated","Weight":0.99,"ID":"dax_have_report_criteria"}]},"sale_has_dax_cog":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.cog":{"Target":{"Entity":"dax.cog"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.cog"}},"State":"Generated","Weight":0.99,"ID":"sales_have_cog"}]},"sale_has_dax_profit":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.profit":{"Target":{"Entity":"dax.profit"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.profit"}},"State":"Generated","Weight":0.99,"ID":"sales_have_profit"}]},"dax_has_sales_by_product":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.sales_by_product":{"Target":{"Entity":"dax.sales_by_product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.sales_by_product"}},"State":"Generated","Weight":0.99,"ID":"dax_have_sales_by_product"}]},"dax_has_sales_by_product_txt":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.sales_by_product_txt":{"Target":{"Entity":"dax.sales_by_product_txt"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.sales_by_product_txt"}},"State":"Generated","Weight":0.99,"ID":"dax_have_sales_by_product_txt"}]},"dim_product_has_dax_sales_average":{"Binding":{"ConceptualEntity":"DimProduct"},"State":"Generated","Roles":{"dim_product":{"Target":{"Entity":"dim_product"}},"dax.sales_average":{"Target":{"Entity":"dax.sales_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"dax.sales_average"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_sales_average"}]},"sale_has_dax_sales_average":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.sales_average":{"Target":{"Entity":"dax.sales_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.sales_average"}},"State":"Generated","Weight":0.99,"ID":"sales_have_sales_average"}]},"dim_product_has_dax_COGS_average":{"Binding":{"ConceptualEntity":"DimProduct"},"State":"Generated","Roles":{"dim_product":{"Target":{"Entity":"dim_product"}},"dax.COGS_average":{"Target":{"Entity":"dax.COGS_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"dax.COGS_average"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_COGS_average"}]},"sale_has_dax_COGS_average":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.COGS_average":{"Target":{"Entity":"dax.COGS_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.COGS_average"}},"State":"Generated","Weight":0.99,"ID":"sales_have_COGS_average"}]},"dim_product_has_dax_profit_average":{"Binding":{"ConceptualEntity":"DimProduct"},"State":"Generated","Roles":{"dim_product":{"Target":{"Entity":"dim_product"}},"dax.profit_average":{"Target":{"Entity":"dax.profit_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"dax.profit_average"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_profit_average"}]},"sale_has_dax_profit_average":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dax.profit_average":{"Target":{"Entity":"dax.profit_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dax.profit_average"}},"State":"Generated","Weight":0.99,"ID":"sales_have_profit_average"}]},"dax_has_sales_average_yyyymm":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.sales_average_yyyymm":{"Target":{"Entity":"dax.sales_average_yyyymm"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.sales_average_yyyymm"}},"State":"Generated","Weight":0.99,"ID":"dax_have_sales_average_yyyymm"}]},"dax_has_COGS_average_yyyymm":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.COGS_average_yyyymm":{"Target":{"Entity":"dax.COGS_average_yyyymm"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.COGS_average_yyyymm"}},"State":"Generated","Weight":0.99,"ID":"dax_have_COGS_average_yyyymm"}]},"dax_has_profit_average_yyyymm":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.profit_average_yyyymm":{"Target":{"Entity":"dax.profit_average_yyyymm"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.profit_average_yyyymm"}},"State":"Generated","Weight":0.99,"ID":"dax_have_profit_average_yyyymm"}]},"dax_has_measure":{"Binding":{"ConceptualEntity":"DAX"},"State":"Generated","Roles":{"dax":{"Target":{"Entity":"dax"}},"dax.measure":{"Target":{"Entity":"dax.measure"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"dax"},"Object":{"Role":"dax.measure"}},"State":"Generated","Weight":0.99,"ID":"dax_have_measure"}]},"sale_has_date1":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"date":{"Target":{"Entity":"date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"date"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dates1"},{"Attribute":{"Subject":{"Role":"date"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"dates_have_sales"}]},"sale_has_dim_segment":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dim_segment":{"Target":{"Entity":"dim_segment"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dim_segment"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dim_segments"},{"Attribute":{"Subject":{"Role":"dim_segment"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"dim_segments_have_sales"}]},"sale_has_dim_country":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dim_country":{"Target":{"Entity":"dim_country"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dim_country"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dim_countries"},{"Attribute":{"Subject":{"Role":"dim_country"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"dim_countries_have_sales"}]},"sale_has_dim_product":{"Binding":{"ConceptualEntity":"Sales"},"State":"Generated","Roles":{"sale":{"Target":{"Entity":"sale"}},"dim_product":{"Target":{"Entity":"dim_product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale"},"Object":{"Role":"dim_product"}},"State":"Generated","Weight":0.99,"ID":"sales_have_dim_products"},{"Attribute":{"Subject":{"Role":"dim_product"},"Object":{"Role":"sale"}},"State":"Generated","Weight":0.99,"ID":"dim_products_have_sales"}]},"date_date_hierarchy_has_year":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date.date_hierarchy":{"Target":{"Entity":"date.date_hierarchy"}},"date.date_hierarchy.year":{"Target":{"Entity":"date.date_hierarchy.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date.date_hierarchy"},"Object":{"Role":"date.date_hierarchy.year"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_years"}]},"date_date_hierarchy_has_quarter":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date.date_hierarchy":{"Target":{"Entity":"date.date_hierarchy"}},"date.date_hierarchy.quarter":{"Target":{"Entity":"date.date_hierarchy.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date.date_hierarchy"},"Object":{"Role":"date.date_hierarchy.quarter"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_quarters"}]},"date_date_hierarchy_has_month":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date.date_hierarchy":{"Target":{"Entity":"date.date_hierarchy"}},"date.date_hierarchy.month":{"Target":{"Entity":"date.date_hierarchy.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date.date_hierarchy"},"Object":{"Role":"date.date_hierarchy.month"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_months"}]},"date_date_hierarchy_has_date":{"Binding":{"ConceptualEntity":"Date"},"State":"Generated","Roles":{"date.date_hierarchy":{"Target":{"Entity":"date.date_hierarchy"}},"date.date_hierarchy.date":{"Target":{"Entity":"date.date_hierarchy.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"date.date_hierarchy"},"Object":{"Role":"date.date_hierarchy.date"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_dates"}]}},"Agents":{"Internal":{"Version":"1.0.0"}}}
				contentType: json

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBIDesktopVersion = 2.142.928.0 (25.04)+de52df9f0bb74ad93a80d89c52d63fe6d07e0e1b

		annotation PBI_QueryOrder = ["DimSegment","DimCountry","DimProduct"]

		annotation PBI_ProTooling = ["TMDLView_Desktop","DaxQueryView_Desktop","DevMode"]

