DEFINE
	// FUNCTION FMAXX = (_measure: expr) =>
	// 	VAR CY = _measure
	// 	VAR Result = MAXX(
	// 		ALLSELECTED('Product'[Brand]),
	// 		_measure
	// 	) - _measure
	// 	RETURN
	// 		Result

	// FUNCTION FYOY = (_measure: expr) =>
	// VAR CY = _measure
	// VAR PY = CALCULATE(
	// 	_measure,
	// 	DATEADD(
	// 		'Date'[Date],
	// 		-1,
	// 		YEAR
	// 	)
	// )
	// VAR Result = CY - PY
	// RETURN
	// 	   Result

	// FUNCTION FPY = (_measure: expr) =>
	// VAR CY = _measure
	// VAR Result = CALCULATE(
	// 	_measure,
	// 		DATEADD(
	// 			'Date'[Date],
	// 				-1,
	// 				YEAR
	// 			)
	// 		)
	// RETURN
	// 		Result

	// FUNCTION FCOLOR = (_measure: expr) =>
	// 	VAR CY = _measure
	// 	VAR PY = CALCULATE(
	// 		_measure,
	// 		DATEADD(
	// 			'Date'[Date],
	// 			-1,
	// 			YEAR
	// 		)
	// 	)
	// 	VAR Result = DIVIDE(
	// 		_measure,
	// 		PY
	// 	) - 1
	// 	RETURN
	// 		SWITCH(
	// 			TRUE(),
	// 			Result > 0, "Lime",
	// 			Result < 0, "Orange",
	// 			BLANK()
	// 		)

	// FUNCTION FLASTREFRESHDATE = (_measure: expr) =>
	// 	VAR FTIME = TIME(
	// 		2,
	// 		0,
	// 		0
	// 	)
	// 	VAR Result = _measure + FTIME
	// 	RETURN
	// 		Result

	// FUNCTION FREFLINE1 = (A) => A
	// FUNCTION FREFLINE2 = (A) => A
	// FUNCTION FREFLINE3 = (A) => A
	// FUNCTION FREFLINE4 = (A) => A
	// FUNCTION FREFLINE5 = (A) => A

	// FUNCTION FVERSION = (A) => A

	FUNCTION FLOWERBOUND = (A) => A
EVALUATE
	{
		FORMAT(
			FLOWERBOUND(2),
			"0.0%"
		)
	}