table DAX
	lineageTag: 7d468fd2-829e-4cfd-938c-4fdb43dbdfdd

	measure Sales =
			
			// Calculate the total (sum) of the [Sales] column in the Sales table
			SUM ( 'Sales'[Sales] )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 95b13e45-b786-46bb-b6eb-b21403f22f25

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Report Criteria' =
			
			// Create a report criteria string by combining selected values for country, discount segment, and date
			VAR __country =
			    SELECTEDVALUE ( DimCountry[Country] ) // Get the selected country from the DimCountry table
			VAR __discount =
			    SELECTEDVALUE ( DimSegment[Segment] ) // Get the selected segment from the DimSegment table
			VAR __date =
			    SELECTEDVALUE ( 'Date'[Year] ) // Get the selected Year from the Date table
			// Combine the selected values into a single string result
			VAR Result = __country & ", " & __discount & ", " & __date // Concatenate country, discount, and date values
			// Return the combined result
			RETURN
			    "Quick summary" & UNICHAR ( 10 ) & Result
		lineageTag: 12e7dbd0-2f23-4933-ad98-e051096d7ece

	measure COGS =
			
			// Calculate the Total Cost of Goods Sold (COGS)
			SUM ( Sales[COGS] )
			// Sum the values in the 'COGS' column of the 'Sales' table
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5fd19a27-f705-4915-a268-5a9f572cc958

	measure Profit =
			
			// Calculate the Profit by subtracting COGS from Sales
			[Sales] - [COGS]
			// Subtract the calculated COGS measure from the Sales measure
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4942789f-e5a6-483a-b447-11954cefb813

	measure 'Sales by Product' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
			VAR Result =
			    SWITCH ( TRUE (), [Sales] = __max, "Green", [Sales] = __min, "Red", "#061953" )
			RETURN
			    Result
		lineageTag: 61a828f0-9c27-442e-8164-cebfd40a880e

	measure 'COGS by Product' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
			VAR Result =
			    SWITCH ( TRUE (), [COGS] = __max, "Red", [COGS] = __min, "Green", "#061953" )
			RETURN
			    Result
		lineageTag: ac9712db-1622-4d86-b4dc-c148dc101a33

	measure 'Profit by Product' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
			VAR Result =
			    SWITCH (
			        TRUE (),
			        [Profit] = __max, "Green",
			        [Profit] = __min, "Red",
			        "#061953"
			    )
			RETURN
			    Result
		lineageTag: e5ed3103-0105-49a6-b613-d1afbcd25b44

	measure 'COGS by Product (txt)' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [COGS] )
			VAR Result =
			    SWITCH (
			        TRUE (),
			        [COGS] = __max, "#605E5C",
			        [COGS] = __min, "#605E5C",
			        "#FFFFFF00"
			    )
			RETURN
			    Result
		lineageTag: 68fd26aa-3c57-4cd8-8960-41df0ab46994

	measure 'Sales by Product (txt)' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Sales] )
			VAR Result =
			    SWITCH (
			        TRUE (),
			        [Sales] = __max, "#605E5C",
			        [Sales] = __min, "#605E5C",
			        "#FFFFFF00"
			    )
			RETURN
			    Result
		lineageTag: 52138b28-7416-4aee-a771-bccebab40ee0

	measure 'Profit by Product (txt)' =
			
			VAR __min =
			    MINX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
			VAR __max =
			    MAXX ( ALLSELECTED ( DimProduct[Product] ), [Profit] )
			VAR Result =
			    SWITCH (
			        TRUE (),
			        [Profit] = __max, "#605E5C",
			        [Profit] = __min, "#605E5C",
			        "#FFFFFF00"
			    )
			RETURN
			    Result
		lineageTag: b87f566b-83ca-4fe8-b847-baf179038c98

	measure 'Sales Average' =
			
			CALCULATE ( AVERAGEX ( DimProduct, [Sales] ), ALLSELECTED () )
		lineageTag: 48d14fe7-07ee-41e5-95ef-13339798e355

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS Average' =
			
			CALCULATE ( AVERAGEX ( DimProduct, [COGS] ), ALLSELECTED () )
		lineageTag: c1345d5a-eafe-46e7-9b94-85cdc6c6075c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Average' =
			
			CALCULATE ( AVERAGEX ( DimProduct, [Profit] ), ALLSELECTED () )
		lineageTag: 6d3d8dc7-ec9a-4b81-b854-0906b5991638

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Average (yyyy-mm)' =
			
			CALCULATE (
			    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [Sales] ),
			    ALLSELECTED ()
			)
		lineageTag: c9c9c1bd-77df-4f3e-a28b-338280e7c73f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS Average (yyyy-mm)' =
			
			CALCULATE (
			    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [COGS] ),
			    ALLSELECTED ()
			)
		lineageTag: 03a09135-1589-4d20-b714-0ac32d46b675

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Average (yyyy-mm)' =
			
			CALCULATE (
			    AVERAGEX ( ALLSELECTED ( 'Date'[Year Month] ), [Profit] ),
			    ALLSELECTED ()
			)
		lineageTag: 95591961-961d-4920-a964-def36981345e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		lineageTag: 95c16aea-39aa-4608-95f9-82bfdf688a2a
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition DAX = calculated
		mode: import
		source = ```
				
				{
				    // A single row table with one column (no name assigned) and one empty string value
				    ""
				}
				
				```

	annotation PBI_Id = 883e31ddacaa4275a2a895b954edf633

