table DimCountry
	lineageTag: d302a70b-52fd-4d8a-93cd-06bad00ca483

	column Country
		dataType: string
		lineageTag: afdc2b06-98c2-4f44-88dc-cb1a2967012b
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column ID_Country
		dataType: int64
		formatString: 0
		lineageTag: ca4b5ae5-a646-40c4-a0cf-64127e1854bc
		summarizeBy: none
		sourceColumn: ID_Country

		annotation SummarizationSetBy = Automatic

	partition DimCountry = m
		mode: import
		source = ```
				let
				    // Step 1: Decode and decompress the Base64 string, then convert the JSON to a table
				    Source = Table.FromRows(
				        Json.Document(
				            Binary.Decompress(
				                Binary.FromText(
				                    "i45Wck7MS0xJVNJRMlSK1YlWck8tyk3MqwTyjcB8t6LEvORUINcYzPVNrchMzgdyTcDc0GBHINtUKTYWAA==", 
				                    BinaryEncoding.Base64
				                ), 
				                Compression.Deflate
				            )
				        ),
				        // Define the column types (both as nullable text initially)
				        let _t = ((type nullable text) meta [Serialized.Text = true]) 
				        in type table [Country = _t, ID_Country = _t]
				    ),
				
				    // Step 2: Convert column types to appropriate types
				    // "Country" -> text
				    // "ID_Country" -> 64-bit integer
				    #"Changed Type" = Table.TransformColumnTypes(
				        Source,
				        {{"Country", type text}, {"ID_Country", Int64.Type}}
				    )
				
				in
				    // Output the final transformed table
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

