DEFINE
    MEASURE 'GEMINI'[@AGE_DATEDIFF] = // Get today's date.
VAR TodayDate =
    TODAY ()

// Extract the current year.
VAR CurrentYear =
    YEAR ( TodayDate )

// Construct the birthday date for the current year (January 28th).
VAR BirthdayThisYear =
    DATE ( CurrentYear, 01, 28 )

// Calculate the number of days until or since the birthday.
VAR Result =
    SWITCH (
        TRUE (),
        TodayDate >= BirthdayThisYear, // If today's date is on or after the birthday this year...
            DATEDIFF (
                BirthdayThisYear, // ...calculate the number of days *since* the birthday. This will be a positive number.
                TodayDate,
                DAY
            ),
        DATEDIFF ( // Otherwise (today's date is before the birthday this year)...
            DATE ( CurrentYear - 1, 01, 28 ), // ...construct the birthday date for the *previous* year.
            TodayDate, // ...calculate the number of days *since* the birthday last year. This will be a negative number, representing days *until* the next birthday.
            DAY
        )
    )

// Return the formatted string containing:
// 1. Days since last birthday (or until next birthday - negative value)
// 2. Remaining days until the *next* birthday.  Relies on a measure "[Number of days]", which likely represents the total number of days in the current year.
// 3. Percentage of the year passed (or remaining if Result is negative)
// 4. Percentage of the year remaining (or passed if Result is negative)
RETURN
    "+" & Result & " | " &
    "-" & [Number of days] - Result & " | " &
    "+" & FORMAT ( DIVIDE ( Result, [Number of days] ), "0.00%" ) & " | " &
    "-" & FORMAT ( 1 - DIVIDE ( Result, [Number of days] ), "0.00%" )

EVALUATE
    SUMMARIZECOLUMNS(
        "@AGE_DATEDIFF", 'GEMINI'[@AGE_DATEDIFF]
    )